### ISSUE TITLE
Is the library still relevant.Can I use it for production.

### ISSUE THREAD

**Issue by greenspand** [romainpiel/Michelangelo#5]
Hi Romain,
I have an app that has a ton of custom compound views. I use Butterknife for my Activites and fragments but The majority of my views are nested inside custom views.
I was thinking to use your library in order to leverage boilerplate overhead. Is the library still valid. can I use with the assurence that in 9 months it woun't break. I would use it for production.
Thx in advance for your reply.

**Comment by romainpiel** [comment]
Hey,
I am not planning to maintain this library in the future but you can take the 6 classes and put them in your project. It's not a complicated code, I'm pretty sure you can work out how to use and correct it if you find any issue.. See it as a helper library ;)

**Comment by greenspand** [comment]
Thx for your feedback. A pity that it will be discontinued. Will take your advice. Cheers.
